### ISSUE TITLE
build issue from bioconductor

### ISSUE THREAD

**Issue by rvitancol** [Nanostring-Biostats/NanoStringNCTools#1]
- [x] Description file: * Checking for valid maintainer...
    * ERROR: Do not use Author/Maintainer fields. Use Authors@R.

- [x] Unit Tests
* checking tests ...
  Running run_unitTests.R [14s/14s]
 [15s/15s] ERROR
Running the tests in tests/run_unitTests.R failed.
Last 20 lines of output:
       test_NanoStringRccSet_valid_signatures 
  
     test_NanoStringRccSet-munge.R 
       /home/pkgbuild/packagebuilder/workers/jobs/1815/NanoStringNCTools_20201216223312/NanoStringNCTools.Rcheck/NanoStringNCTools/unitTests/test_NanoStringRccSet-munge.R 
  
     test_NanoStringRccSet-signatures.R 
       /home/pkgbuild/packagebuilder/workers/jobs/1815/NanoStringNCTools_20201216223312/NanoStringNCTools.Rcheck/NanoStringNCTools/unitTests/test_NanoStringRccSet-signatures.R 
  
     test_NanoStringRccSet-subset.R 
       /home/pkgbuild/packagebuilder/workers/jobs/1815/NanoStringNCTools_20201216223312/NanoStringNCTools.Rcheck/NanoStringNCTools/unitTests/test_NanoStringRccSet-subset.R 
  
     test_NanoStringRccSet-summary.R 
       /home/pkgbuild/packagebuilder/workers/jobs/1815/NanoStringNCTools_20201216223312/NanoStringNCTools.Rcheck/NanoStringNCTools/unitTests/test_NanoStringRccSet-summary.R 
  
     test_NanoStringRccSet-utils.R 
       /home/pkgbuild/packagebuilder/workers/jobs/1815/NanoStringNCTools_20201216223312/NanoStringNCTools.Rcheck/NanoStringNCTools/unitTests/test_NanoStringRccSet-utils.R 
  
  
  Error in BiocGenerics:::testPackage("NanoStringNCTools") : 
    unit tests failed for package NanoStringNCTools

- [x] * Checking for bioc-devel mailing list subscription...
    * ERROR: Maintainer must subscribe to the bioc-devel mailing list.
      Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel

**Comment by rvitancol** [comment]
see build report for more details of the error
http://bioconductor.org/spb_reports/GeomxTools_buildreport_20201216173544.html#malbec2_buildsrc_anchor

**Comment by zhiiiyang** [comment]
Fix the error on authors under my branch `zyang`. 
![image](https://user-images.githubusercontent.com/7269113/102448390-e0b63e80-3fe6-11eb-89ac-16fe3b840062.png)
