### ISSUE TITLE
Tutorial link

### ISSUE THREAD

**Issue by amarinderthind** [Nanostring-Biostats/NanoStringNCTools#12]
Could you please provide the tutorial link on the Github page? or relevant documents

**Comment by NicoleEO** [comment]
@amarinderthind, we are working on getting the readme up. If you need some guidance in the meantime here is a link to the vignette: https://github.com/Nanostring-Biostats/NanoStringNCTools/tree/master/vignettes.

**Comment by amarinderthind** [comment]
Thanks, it seems package requires R 4.1. However, there are a few issues while installing R 4.1 (Pre-release) for the window. Do you have any suggestions?

**Comment by zhiiiyang** [comment]
@amarinderthind, the description lists the R version to be >=3.6. If you can't install it from Bioconductor due to the lower R version, you can also try `devtools::install_github("Nanostring-Biostats/NanoStringNCTools")`

https://github.com/Nanostring-Biostats/NanoStringNCTools/blob/master/DESCRIPTION#L10

**Comment by amarinderthind** [comment]
Hi! Sorry to bother you. I can't find a proper document, particularly how to interpret the geometric mean of the housekeeping plot. If it fails, does it mean hk genes frequently detected below the Limit of detection (LOD)? And in this case, i might be changing the hk genes, or if not, then I should exclude the sample with flags.

**Comment by NicoleEO** [comment]
Hi @amarinderthind, please refer to our support site for assay questions. Our FAQ page, https://www.nanostring.com/support/documentation/knowledge-base-faqs/#data-analysis-and-normalization-general, may be of interest. Feel free to reach out to our support group if you have additional questions: support@nanostring.com.
