### ISSUE TITLE
Prajan's comments on NCTools vignette

### ISSUE THREAD

**Issue by rvitancol** [Nanostring-Biostats/NanoStringNCTools#15]
- [x] Add this to intro:
## Introduction

The NanostringNCTools package enables independent analysis of NanoString nCounter data (e.g. RCC/RLF data) in R.

In this vignette we will:
- Create a Nanostring data object (e.g. NanoStringRCCSet) integrating RCC + RLF + Annotation data
- Learn to summarize, subset, transform the data object
- Perform and visualize quality control assessments of the data
- Perform data normalization for downstream analyses 

NanoStringRCCSet was inherited from Biobase's ExpressionSet class. The NanoStringRCCSet class was designed to encapsulate data and corresponding methods for Nanostring RCC files generated from the NanoString nCounter platform.

- [x] For QC PDiv: User inputs? What decisions do they make?
- [x] For normalization: 
PDiv:Options include other normalization options and how to choose?
- [x] check demoData plots for QC only has 2 lanes
- [x] check demoData plots for QC only has 2 lanes for binding density
- [x] labels for plots, label axis and descriptions for plots, ensure that it is labeled or explained
- [x] if plots can take additional inputs, state and explain
- [x] description of what each code line does. like walking the reader on what is happening in the code.
- [x] how to change annotation to show in the analysis (for QC, plots, normalization)
- [x] Show heatmap after normalization
- [x] Briefly explain each part - like what is binding density, etc. can reference 360 report.

**Comment by NicoleEO** [comment]
@yuqiren can you mark off what has been completed in this list on your latest update?

**Comment by yuqiren** [comment]
> @yuqiren can you mark off what has been completed in this list on your latest update?

All issues in the checklist should be addressed. I marked them off.

**Comment by NicoleEO** [comment]
thanks @yuqiren, closing this issue now.
