### ISSUE TITLE
Bug/typo with normalization calculations in NanoStringRccSet-normalize.R

### ISSUE THREAD

**Issue by nranthony** [Nanostring-Biostats/NanoStringNCTools#28]
Normalization values do not match those calculated using nSolver.

I suspect that `object` on line 13 should be `posCtrl` from the line above:

`posCtrl <- positiveControlSubset(object)`
https://github.com/Nanostring-Biostats/NanoStringNCTools/blob/e1504e2c25463dff6f55b7c2f236867119e55889/R/NanoStringRccSet-normalize.R#L13

If I change `object` on line 13 to be `posCtrl` the Content Normalization Factors and resulting normalized counts match that of nSolver.  As it stands the positive control normalization factors are calculated from the entire gene set passed using `object`.

**Comment by NicoleEO** [comment]
Hi @nranthony,

Thanks for using NanoStringNCTools. If you like, feel free to fork and submit a PR to correct.

Thanks,
Nicole

@maddygriz heads up
