### ISSUE TITLE
360 Report Error

### ISSUE THREAD

**Issue by rvitancol** [Nanostring-Biostats/NanoStringNCTools#6]
Error running \\hades\share\Rona\360v110\QC2\BareBonesReport using  NCTools outside Rpackages

Report Error:

Quitting from lines 170-203 (BareBonesReport.Rmd) 
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': values must be length 1,
 but FUN(X[[1]]) result is length 17
Calls: <Anonymous> ... .local -> .sigCalc -> t -> vapply -> .handleSimpleError -> h
Execution halted

**Comment by zhiiiyang** [comment]
The report can be knitted without errors. See report here 
\hades\share\Rona\360v110\QC2\
