### ISSUE TITLE
360 Related Issues - Plots

### ISSUE THREAD

**Issue by rvitancol** [Nanostring-Biostats/NanoStringNCTools#7]
Report related issues:
http://hades:62495/files/hades/Rona/360v110/QC2/BareBonesReport.html#quality-control-details

- [x] HK QC plots display RCC file names instead of sample names
![image](https://user-images.githubusercontent.com/55164869/104062242-f4506180-51ae-11eb-8ee4-c57ccb6eb761.png)

- [x] LOD QC plots 
![image](https://user-images.githubusercontent.com/55164869/104062308-121dc680-51af-11eb-93c3-612cdb9c949d.png)

**Comment by rvitancol** [comment]
LOD plot boxplots still display only one boxplot for all samples.
![image](https://user-images.githubusercontent.com/55164869/104209221-47602980-53e6-11eb-9378-4dbf4cd668c2.png)

**Comment by NicoleEO** [comment]
@rvitancol can you point me to your config. I think I need to step through to find the issue.

**Comment by rvitancol** [comment]
@NicoleEO 
\\hades\share\Rona\360v110\QC2\BareBonesReport

**Comment by NicoleEO** [comment]
@rvitancol the LOD plot is fixed now.
